{% set name = "flask-muck" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/flask_muck-{{ version }}.tar.gz
  sha256: b4616dddff641f66b8a0289764fcfb2cacb273c9f5f12c69417e408374bb0f9b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - hatchling
    - pip
  run:
    - python >=3.9
    - flask >=1.4.0
    - webargs >=8.0.0
    - marshmallow >=3.15.0
    - pydantic >=2.0
    - apispec >= 6.3.0
    - rich >=13.7.0
    - pyhumps >=3.8.0
    - flasgger >=0.9.7.1
    - marshmallow-jsonschema >=0.13.0

test:
  imports:
    - flask_muck
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dtiesling/flask-muck
  doc_url: https://dtiesling.github.io/flask-muck/
  summary: Batteries included framework for generating RESTful apis using Flask and SqlAlchemy.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
