{% set name = "flask-muck" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/flask_muck-{{ version }}.tar.gz
  sha256: f0bc5d12894899925fd68dd0d7881b9b7543b031329875f91e1f0ab71675a729

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - hatchling
    - poetry-core
    - pip
  run:
    - python >=3.9
    - flask >=2.0.0
    - sqlalchemy >=1.4.0
    - webargs >=8.0.0
    - marshmallow >=3.15.0
    - pydantic >=2.0
    - mkdocstrings >=0.24.0,<0.25.0

test:
  imports:
    - flask_muck
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dtiesling/flask-muck
  doc_url: https://dtiesling.github.io/flask-muck/
  summary: Batteries included framework for generating RESTful apis using Flask and SqlAlchemy.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
